### ISSUE TITLE
Web Development: Education Planning

### ISSUE THREAD

**Issue by KL1217** [hicodingclub/askmschen-front#13]
This task is to program the Education Planning part of the Service Page.

Click the link below to follow the layout.
https://www.figma.com/file/j9pO5DfFZLxuuHgpJFtIYK/Education-Planning?node-id=1%3A2

Deadline 8/25/20

Please assign yourself to the task.

Volunteer hours granted for completion of the task: 2 hours

**Comment by clairey21** [comment]
[education-planning.zip](https://github.com/hicodingclub/askmschen-front/files/5121772/education-planning.zip)
