### ISSUE TITLE
Web Development: Travel and Camps

### ISSUE THREAD

**Issue by KL1217** [hicodingclub/askmschen-front#14]
This task is to program the Travel and Camps part of the Service Page.

Click the link below to follow the layout.
https://www.figma.com/file/BLUmzMnzCNHzrZmkvhbddP/Travel-and-Camps?node-id=1%3A2

Deadline 8/25/20

Please assign yourself to the task.

Volunteer hours granted for completion of the task: 2 hours

**Comment by yufanwang07** [comment]
First crude result. Please read the README.md file given with the zip.

[Mschen TravelCamp.zip](https://github.com/hicodingclub/askmschen-front/files/5113336/Mschen.TravelCamp.zip)

**Comment by yufanwang07** [comment]
First revision. Please read the README.md file given with the zip.
EDIT: Most of the extra CSS is deleted. There are still some extras that I might need for future revisions.
FIXED: Button CSS animations, minor errors in modal javascript.
FIXED: Minor text sizing and spacing issues.

[Mschen TravelCamp1.zip](https://github.com/hicodingclub/askmschen-front/files/5113339/Mschen.TravelCamp.zip)

**Comment by yufanwang07** [comment]
Last revision.
EDIT: Deleted all extra CSS.

[Mschen TravelCamp.zip](https://github.com/hicodingclub/askmschen-front/files/5126626/Mschen.TravelCamp.zip)
