### ISSUE TITLE
Web Development: School Application and Transfer

### ISSUE THREAD

**Issue by KL1217** [hicodingclub/askmschen-front#15]
This task is to program the School Application and Transfer part of the Service Page.

Click the link below to follow the layout.
https://www.figma.com/file/zKKyu5hLPmYFkhD6ykw00z/School-Application-and-Transfer?node-id=0%3A1

Deadline 8/25/20

Please assign yourself to the task.

Volunteer hours granted for completion of the task: 2 hours

**Comment by akashamalNA** [comment]
[MsChen.AppTransfer.zip](https://github.com/hicodingclub/askmschen-front/files/5121627/MsChen.AppTransfer.zip)

Basic page using the same CSS and formatting as Yufan.

**Comment by akashamalNA** [comment]
[MsChen.AppTransferV2.zip](https://github.com/hicodingclub/askmschen-front/files/5132832/MsChen.AppTransferV2.zip)

FIX: Table now shows up when on a smaller windows size.
