### ISSUE TITLE
AskMsChen Logo

### ISSUE THREAD

**Issue by WilliamShih1234** [hicodingclub/askmschen-front#2]
Color Theme: Black: 000000, White: FFFFFF, Grey: A4A4A4, Blue: 1377D4
Feel free to use other colors 

**Logo** 
Create a Logo for our counselor project. The name of the website is “AskMsChen”. Use your imagination for a sophisticated and appealing logo design. Keep in mind that this is a counselor’s website so design your logo in that direction. You can use the color theme provided and more colors of your choice. 

*Number of people: Unlimited  
Volunteer Hours: 1.5 hours*

**Comment by samwich-song** [comment]
https://www.figma.com/file/om3ZvjClNbhPp2KsCB7dZB/AskMsChen-Logo?node-id=3%3A0

**Comment by whichlee** [comment]
https://www.figma.com/file/WEHLnqZmXdnn9DjmFWl5Z1/AskMsChen-Logo?node-id=0%3A1
