### ISSUE TITLE
Home Page

### ISSUE THREAD

**Issue by WilliamShih1234** [hicodingclub/askmschen-front#3]
Any colors of your choice
Must include the following:
Picture slideshow section (put placeholders)
Intro area with mission statement and place for her to say a little bit about herself
News: space for latest news posts (put placeholders)
Quote section: for past student thoughts and quotes
Links: links and pictures that connect to all other pages on her website (services, products, blog, and resources)
Subscribe: place for people to enter their email to subscribe to her latest news
Contact Us: Include logos of wechat, youtube, bilibili and have space for her phone number and email
Deadline 7/1/20
Please assign yourself to the task, we need your participation
Volunteer hours granted for completion of task: 5 hours

Please use this website as a reference: https://www.collegeessayguy.com/

**Comment by booki1** [comment]
Sorry this came so late! 
https://www.figma.com/file/1wM2BJRQ2hGhKqqevisZIQ/amc-service-page?node-id=2%3A2
Did w/ Natasha, ended up w Homepage & Services page on the same Figma thing haha
