### ISSUE TITLE
Services Page:

### ISSUE THREAD

**Issue by WilliamShih1234** [hicodingclub/askmschen-front#4]
Include the following 
Header including an image and heading saying e.g. “these are the services I provide”
4 Links to subpages that are: US Homestay, Education Planning, Travel and Camps, and School Application and Transfer
Create a good layout and do not worry about images and links 
Deadline 7/8/20
Please assign yourself to the task, we need your participation
Volunteer hours granted for completion of the task: 3 hours

**Comment by whichlee** [comment]
Created with Caroline Wang!
https://www.figma.com/file/1wM2BJRQ2hGhKqqevisZIQ/amc-service-page?node-id=2%3A2
