### ISSUE TITLE
UI Design: College Picture

### ISSUE THREAD

**Issue by WilliamShih1234** [hicodingclub/askmschen-front#9]
The counselor wants to create a picture including the logo and name of the colleges her students have gotten into. Create a picture collection of logos and names of the following colleges. Make the logos/names of different sizes. The final collection should be wider than taller. Use at least 8 and at most 20 colleges from below.

Refer to the below image:
![images](https://user-images.githubusercontent.com/42718829/89443340-ffd1c500-d704-11ea-93f5-15288ce98726.png)

Colleges to choose from: Uchicago, USC, Notre Dame, UNC, UCB, UCLA, UCSB, UCSD, Vanderbilt, NYU, RISD, SVA, Leigh, Bates, Tufts, Boston College, Skidmore, Carlton, Northeastern, Purdue, UIUC, Oxford, ICL, University of Toronto.

Please assign yourself to the task

Volunteer hours granted for completion of the task: 1.5 hours

**Comment by adac000** [comment]
https://www.figma.com/file/T8Nq1p4pZdp0Jy0Ctqtewu/Ms.-Chen-College-Picture-9?node-id=0%3A1

**Comment by WilliamShih1234** [comment]
Good work!

**Comment by adac000** [comment]
Thank you!
